version: '3.3'

services:
    translation_proxy:
        build:
            context: ./proxy 
        environment: 
            - MODEL_PATH=data
        command: python app.py
        ports:
            - "5000:5000"

    en_jap:
        image: translation_base
        environment:
            - MODEL_PATH=data
            - SOURCE_LANG=en
            - TARGET_LANG=jap
        command: python app.py
        volumes:
            - ./data:/app/data

    jap_en:
        image: translation_base
        environment:
            - MODEL_PATH=data
            - SOURCE_LANG=jap
            - TARGET_LANG=en
        command: python app.py
        volumes:
            - ./data:/app/data

volumes:
    data: