version: '3.3'

services:
    translation_proxy:
        build:
            context: ./proxy 
        environment: 
            - MODEL_PATH=data
        command: python app.py

    translation_base:
        image: translation_base
        build:
            context: .
            dockerfile: Dockerfile

    en_jap:
        image: translation_base
        environment:
            - MODEL_PATH=data
            - SOURCE_LANG=en
            - TARGET_LANG=jap
            - FLASK_PORT=5000
        command: python app.py
        
    jap_en:
        image: translation_base
        environment:
            - MODEL_PATH=data
            - SOURCE_LANG=jap
            - TARGET_LANG=en
            - FLASK_PORT=5001
        command: python app.py
