apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: translation-proxy
  name: translation-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: translation-proxy
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: translation-proxy
    spec:
      containers:
      - args:
        - python
        - app.py
        env:
        - name: MODEL_PATH
          value: data
        image: translation-proxy
        imagePullPolicy: ""
        name: translation-proxy
        ports:
        - containerPort: 5000
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
